#!/bin/bash
#    Begin PBS directives
#PBS -N 2bcs1
#PBS -M wjiang18@ornl.gov
#PBS -l nodes=1:ppn=8
#PBS -l walltime=24:00:00
#PBS -W group_list=cades-nucphys
#PBS -A nucphys
#PBS -l qos=long
#PBS -q dhigh_mem
#    End PBS directives and begin shell commands
module purge
module load PE-intel
#work_dir=/lustre/or-hydra/cades-nucphys/w01/nuclear_matteri
scratch_dir=/localscratch
#storage_dir=/home/w01/nucleon-scattering/nsopt_inputs/deltafull
cd /lustre/or-hydra/cades-nucphys/w01/output
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_-3.00_cE_-1.00_rho_0.16 > ./output/pnm_28_cD_-3.00_cE_-1.00_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_-2.00_cE_-1.00_rho_0.16 > ./output/pnm_28_cD_-2.00_cE_-1.00_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_-1.00_cE_-1.00_rho_0.16 > ./output/pnm_28_cD_-1.00_cE_-1.00_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_0.00_cE_-1.00_rho_0.16 > ./output/pnm_28_cD_0.00_cE_-1.00_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_1.00_cE_-1.00_rho_0.16 > ./output/pnm_28_cD_1.00_cE_-1.00_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_2.00_cE_-1.00_rho_0.16 > ./output/pnm_28_cD_2.00_cE_-1.00_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_3.00_cE_-1.00_rho_0.16 > ./output/pnm_28_cD_3.00_cE_-1.00_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_-3.00_cE_-0.75_rho_0.16 > ./output/pnm_28_cD_-3.00_cE_-0.75_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_-2.00_cE_-0.75_rho_0.16 > ./output/pnm_28_cD_-2.00_cE_-0.75_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_-1.00_cE_-0.75_rho_0.16 > ./output/pnm_28_cD_-1.00_cE_-0.75_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_0.00_cE_-0.75_rho_0.16 > ./output/pnm_28_cD_0.00_cE_-0.75_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_1.00_cE_-0.75_rho_0.16 > ./output/pnm_28_cD_1.00_cE_-0.75_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_2.00_cE_-0.75_rho_0.16 > ./output/pnm_28_cD_2.00_cE_-0.75_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_3.00_cE_-0.75_rho_0.16 > ./output/pnm_28_cD_3.00_cE_-0.75_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_-3.00_cE_-0.50_rho_0.16 > ./output/pnm_28_cD_-3.00_cE_-0.50_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_-2.00_cE_-0.50_rho_0.16 > ./output/pnm_28_cD_-2.00_cE_-0.50_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_-1.00_cE_-0.50_rho_0.16 > ./output/pnm_28_cD_-1.00_cE_-0.50_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_0.00_cE_-0.50_rho_0.16 > ./output/pnm_28_cD_0.00_cE_-0.50_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_1.00_cE_-0.50_rho_0.16 > ./output/pnm_28_cD_1.00_cE_-0.50_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_2.00_cE_-0.50_rho_0.16 > ./output/pnm_28_cD_2.00_cE_-0.50_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_3.00_cE_-0.50_rho_0.16 > ./output/pnm_28_cD_3.00_cE_-0.50_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_-3.00_cE_-0.25_rho_0.16 > ./output/pnm_28_cD_-3.00_cE_-0.25_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_-2.00_cE_-0.25_rho_0.16 > ./output/pnm_28_cD_-2.00_cE_-0.25_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_-1.00_cE_-0.25_rho_0.16 > ./output/pnm_28_cD_-1.00_cE_-0.25_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_0.00_cE_-0.25_rho_0.16 > ./output/pnm_28_cD_0.00_cE_-0.25_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_1.00_cE_-0.25_rho_0.16 > ./output/pnm_28_cD_1.00_cE_-0.25_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_2.00_cE_-0.25_rho_0.16 > ./output/pnm_28_cD_2.00_cE_-0.25_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_3.00_cE_-0.25_rho_0.16 > ./output/pnm_28_cD_3.00_cE_-0.25_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_-3.00_cE_0.00_rho_0.16 > ./output/pnm_28_cD_-3.00_cE_0.00_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_-2.00_cE_0.00_rho_0.16 > ./output/pnm_28_cD_-2.00_cE_0.00_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_-1.00_cE_0.00_rho_0.16 > ./output/pnm_28_cD_-1.00_cE_0.00_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_0.00_cE_0.00_rho_0.16 > ./output/pnm_28_cD_0.00_cE_0.00_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_1.00_cE_0.00_rho_0.16 > ./output/pnm_28_cD_1.00_cE_0.00_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_2.00_cE_0.00_rho_0.16 > ./output/pnm_28_cD_2.00_cE_0.00_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_3.00_cE_0.00_rho_0.16 > ./output/pnm_28_cD_3.00_cE_0.00_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_-3.00_cE_0.25_rho_0.16 > ./output/pnm_28_cD_-3.00_cE_0.25_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_-2.00_cE_0.25_rho_0.16 > ./output/pnm_28_cD_-2.00_cE_0.25_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_-1.00_cE_0.25_rho_0.16 > ./output/pnm_28_cD_-1.00_cE_0.25_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_0.00_cE_0.25_rho_0.16 > ./output/pnm_28_cD_0.00_cE_0.25_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_1.00_cE_0.25_rho_0.16 > ./output/pnm_28_cD_1.00_cE_0.25_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_2.00_cE_0.25_rho_0.16 > ./output/pnm_28_cD_2.00_cE_0.25_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_3.00_cE_0.25_rho_0.16 > ./output/pnm_28_cD_3.00_cE_0.25_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_-3.00_cE_0.50_rho_0.16 > ./output/pnm_28_cD_-3.00_cE_0.50_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_-2.00_cE_0.50_rho_0.16 > ./output/pnm_28_cD_-2.00_cE_0.50_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_-1.00_cE_0.50_rho_0.16 > ./output/pnm_28_cD_-1.00_cE_0.50_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_0.00_cE_0.50_rho_0.16 > ./output/pnm_28_cD_0.00_cE_0.50_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_1.00_cE_0.50_rho_0.16 > ./output/pnm_28_cD_1.00_cE_0.50_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_2.00_cE_0.50_rho_0.16 > ./output/pnm_28_cD_2.00_cE_0.50_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_3.00_cE_0.50_rho_0.16 > ./output/pnm_28_cD_3.00_cE_0.50_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_-3.00_cE_0.75_rho_0.16 > ./output/pnm_28_cD_-3.00_cE_0.75_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_-2.00_cE_0.75_rho_0.16 > ./output/pnm_28_cD_-2.00_cE_0.75_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_-1.00_cE_0.75_rho_0.16 > ./output/pnm_28_cD_-1.00_cE_0.75_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_0.00_cE_0.75_rho_0.16 > ./output/pnm_28_cD_0.00_cE_0.75_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_1.00_cE_0.75_rho_0.16 > ./output/pnm_28_cD_1.00_cE_0.75_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_2.00_cE_0.75_rho_0.16 > ./output/pnm_28_cD_2.00_cE_0.75_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_3.00_cE_0.75_rho_0.16 > ./output/pnm_28_cD_3.00_cE_0.75_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_-3.00_cE_1.00_rho_0.16 > ./output/pnm_28_cD_-3.00_cE_1.00_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_-2.00_cE_1.00_rho_0.16 > ./output/pnm_28_cD_-2.00_cE_1.00_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_-1.00_cE_1.00_rho_0.16 > ./output/pnm_28_cD_-1.00_cE_1.00_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_0.00_cE_1.00_rho_0.16 > ./output/pnm_28_cD_0.00_cE_1.00_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_1.00_cE_1.00_rho_0.16 > ./output/pnm_28_cD_1.00_cE_1.00_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_2.00_cE_1.00_rho_0.16 > ./output/pnm_28_cD_2.00_cE_1.00_rho_0.16.out &
wait
mpirun  -np 8 ./prog_ccm.exe ./ccm_in_pnm_28_cD_3.00_cE_1.00_rho_0.16 > ./output/pnm_28_cD_3.00_cE_1.00_rho_0.16.out &
wait
