#PBS -N nuclearmatter
#PBS -j eo
#PBS -l walltime=00:05:00,nodes=16
export OMP_NUM_THREADS=16

cd /lustre/or-hydra/cades-nucphys/w01
aprun  -n16 -d16 ./prog_ccm.exe ./ccm_in_snm_28_cD_-3.00_cE_-1.00_rho_0.12 > ./output/snm_28_cD_-3.00_cE_-1.00_rho_0.12.out &
wait
aprun  -n16 -d16 ./prog_ccm.exe ./ccm_in_snm_28_cD_-3.00_cE_-1.00_rho_0.14 > ./output/snm_28_cD_-3.00_cE_-1.00_rho_0.14.out &
wait
aprun  -n16 -d16 ./prog_ccm.exe ./ccm_in_snm_28_cD_-3.00_cE_-1.00_rho_0.16 > ./output/snm_28_cD_-3.00_cE_-1.00_rho_0.16.out &
wait
aprun  -n16 -d16 ./prog_ccm.exe ./ccm_in_snm_28_cD_-3.00_cE_-1.00_rho_0.18 > ./output/snm_28_cD_-3.00_cE_-1.00_rho_0.18.out &
wait
aprun  -n16 -d16 ./prog_ccm.exe ./ccm_in_snm_28_cD_-3.00_cE_-1.00_rho_0.20 > ./output/snm_28_cD_-3.00_cE_-1.00_rho_0.20.out &
wait
